name: Azure DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'  

      - name: Terraform Initialize Workspace
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: terraform init

      - name: Terraform Create Infrastructure Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_ssh_public_key: ${{ secrets.VM_SSH_PUB_KEY }} # <-- ADD THIS LINE
        run: terraform plan

      - name: Terraform Apply Infrastructure Changes
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_ssh_public_key: ${{ secrets.VM_SSH_PUB_KEY }} # <-- ADD THIS LINE
        run: terraform apply -auto-approve
        
      - name: Extract Public IP Address
        id: get_ip
        run: |
          echo "VM_IP=$(terraform output -raw vm_public_ip)" >> $GITHUB_ENV

      - name: Copy Docker Files to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.VM_IP }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          source: "docker-compose.yml,app/index.html"
          target: "/home/azureuser/"

      - name: Execute Multi-Container Multi-Tier App Cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_IP }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/azureuser
            sudo docker-compose up -d --force-recreate